# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Non-HTML is useless until the docs are much longer
formats: []

python:
  version: 3.7
  install:
     - method: setuptools
       path: .
  system_packages: true

# This is _very slow_
#conda:
#  environment: environment.yml
